name: Windows/amd64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - name: Add mingw32 for Windows build
      run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64

    - name: Build for Windows
      run: cargo build --target=x86_64-pc-windows-gnu --release

    - name: Create archive
      run: cp ./target/x86_64-pc-windows-gnu/release/PKT-Voter.exe ./PKT-Voter_windows_amd64.exe
  
    - name: Archive built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PKT-Voter_windows_amd64.exe
        path: PKT-Voter_windows_amd64.exe
  
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
  
    - name: Upload Executable to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .
        asset_name: PKT-Voter_windows_amd64.exe
        asset_content_type: application/octet-stream